name: sweden_roleplay
description: Livestream app Made by Kako
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  ionicons: ^0.2.2
  webview_flutter: ^4.0.0
  webview_windows: ^0.4.0
  flutter_web_auth: ^0.5.0
  shared_preferences: ^2.1.1
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/icons/
     - assets/images/
     - assets/images/banner.gif
     