name: sweden_roleplay
description: Livestream app Made by Kako
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  ionicons: ^0.2.2
  webview_flutter: ^3.0.0

  # Downgraded http_parser to 4.0.2 to resolve conflicts
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/icons/
     - assets/images/
